name: Deploy Firebase

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-firebase:
    name: Deploy Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Deploy Firestore rules and Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules,firestore:indexes,functions --project camperchecks-490115
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
          PROJECT_PATH: ./firebase
